# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-12 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], max_length=11, unique=True)),
            ],
            options={
                'verbose_name': 'Ticket Status',
                'verbose_name_plural': 'Ticket Status',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketStatus'),
        ),
    ]
