# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-12 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190812_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='ticket_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=11, unique=True),
        ),
    ]
