# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-12 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190812_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], max_length=7, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='ticket_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=6, unique=True),
        ),
    ]
