# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-12 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190812_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
    ]
