# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-14 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20190812_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
