# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-15 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_auto_20190815_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(default='3', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
    ]
