# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-18 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_auto_20190815_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('hi', 'hi'), ('Feature', 'Feature')], max_length=7, unique=True),
        ),
    ]
