# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-18 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0040_auto_20190818_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('f', 'f'), ('Feature', 'Feature')], max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(default='2', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.ForeignKey(default='2', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.TicketStatus'),
        ),
    ]
